name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build --no-cache -t app:latest .

      - name: Deploy
        run: docker compose -f ~/apps/docker-compose.yml up -d --no-deps --force-recreate app
